

services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRootPass123   # correct way to set root password
      MYSQL_DATABASE: mydb                 # optional: a database to create
      MYSQL_USER: normaluser               # optional: normal user
      MYSQL_PASSWORD: normalpass           # optional: password for normal user
    ports:
      - "3307:3306"
    networks:
      - ems-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ems-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ems-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ems-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - ems-net

networks:
  ems-net:
    driver: bridge
