FROM node:18-alpine as build

WORKDIR /app

# Clone frontend repo
RUN apk add --no-cache git && \
    git clone https://github.com/premkotha10/cicd_project_frontend.git .

# Install dependencies and build
RUN npm install && npm run build

# Serve frontend with Nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .   # Adjust if build folder is "build" instead of "dist"
EXPOSE 8080

