# Stage 1: Build with Maven and JDK
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Install git
RUN apt-get update && apt-get install -y git

# Clone backend repo
RUN git clone https://github.com/premkotha10/cicd_project_backend.git .

# Build Spring Boot JAR
RUN mvn clean package -DskipTests

# Stage 2: Run the JAR
FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
