version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRootPass123   # correct root password
      MYSQL_DATABASE: eventdb              # database your Spring Boot app uses
      MYSQL_USER: normaluser               # optional user
      MYSQL_PASSWORD: normalpass           # optional user password
    ports:
      - "3307:3306"                        # for accessing MySQL from host
    networks:
      - ems-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ems-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: myRootPass123
    networks:
      - ems-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ems-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - ems-net

networks:
  ems-net:
    driver: bridge

